; ============================================================
;  PlatformIO config for FOG Detector
;  Board: ESP32 Dev Module
; ============================================================

[env:esp32dev]
platform = espressif32
board = esp32-s3-devkitc-1    ; most common ESP32-S3 dev board
upload_port = /dev/cu.usbmodem101
monitor_port = /dev/cu.usbmodem101

framework = arduino
monitor_speed = 115200
upload_speed = 921600

board_build.partitions = default_8MB.csv

lib_deps =
    tanakamasayuki/TensorFlowLite_ESP32 @ ^1.0.0

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=0
    -Os